import Joi from "joi";

export const updateProfileSchema = Joi.object({
  username: Joi.string().alphanum().min(3).max(30).messages({
    "string.alphanum": "Username must only contain alphanumeric characters",
    "string.min": "Username must be at least 3 characters long",
    "string.max": "Username cannot exceed 30 characters",
  }),

  profile: Joi.object({
    firstName: Joi.string().max(50),
    lastName: Joi.string().max(50),
    phoneNumber: Joi.string().pattern(/^[0-9+\-() ]+$/),
    avatar: Joi.string().uri(),
  }).messages({
    "string.max": "Field cannot exceed 50 characters",
    "string.pattern.base": "Invalid phone number format",
    "string.uri": "Avatar must be a valid URL",
  }),
})
  .min(1)
  .messages({
    "object.min": "At least one field is required for update",
  });

export const updateUserRoleSchema = Joi.object({
  role: Joi.string()
    .valid("user", "admin", "moderator", "employee", "editor")
    .required()
    .messages({
      "any.only":
        "Role must be one of: user, admin, moderator, employee, editor",
      "any.required": "Role is required",
    }),
});

export const createUserSchema = Joi.object({
  name: Joi.string().min(2).max(100).required().messages({
    "string.min": "Name must be at least 2 characters long",
    "string.max": "Name cannot exceed 100 characters",
    "any.required": "Name is required",
  }),

  email: Joi.string().email().required().messages({
    "string.email": "Please provide a valid email address",
    "any.required": "Email is required",
  }),

  password: Joi.string().min(6).max(50).required().messages({
    "string.min": "Password must be at least 6 characters long",
    "string.max": "Password cannot exceed 50 characters",
    "any.required": "Password is required",
  }),

  role: Joi.string().valid("employee", "editor").required().messages({
    "any.only": "Role must be either 'employee' or 'editor'",
    "any.required": "Role is required",
  }),

  // employeeId is auto-generated by backend, not accepted from frontend

  contact: Joi.string()
    .pattern(/^[0-9+\-() ]+$/)
    .messages({
      "string.pattern.base": "Invalid contact number format",
    }),

  dateOfJoining: Joi.string(),

  location: Joi.string().max(100).messages({
    "string.max": "Location cannot exceed 100 characters",
  }),

  salary: Joi.number().positive().messages({
    "number.positive": "Salary must be a positive number",
  }),

  workStartTime: Joi.string()
    .pattern(/^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/)
    .messages({
      "string.pattern.base": "Work start time must be in HH:MM format",
    }),

  workEndTime: Joi.string()
    .pattern(/^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/)
    .messages({
      "string.pattern.base": "Work end time must be in HH:MM format",
    }),
});

export const updateUserStatusSchema = Joi.object({
  isActive: Joi.boolean().required().messages({
    "any.required": "isActive field is required",
  }),
});

export const updateEmployeeSchema = Joi.object({
  name: Joi.string().min(2).max(100).messages({
    "string.min": "Name must be at least 2 characters long",
    "string.max": "Name cannot exceed 100 characters",
  }),

  email: Joi.string().email().messages({
    "string.email": "Please provide a valid email address",
  }),

  contact: Joi.string()
    .pattern(/^[0-9+\-() ]+$/)
    .messages({
      "string.pattern.base": "Invalid contact number format",
    }),

  dateOfJoining: Joi.string(),

  location: Joi.string().max(100).messages({
    "string.max": "Location cannot exceed 100 characters",
  }),

  salary: Joi.number().positive().messages({
    "number.positive": "Salary must be a positive number",
  }),

  workStartTime: Joi.string()
    .pattern(/^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/)
    .messages({
      "string.pattern.base": "Work start time must be in HH:MM format",
    }),

  workEndTime: Joi.string()
    .pattern(/^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/)
    .messages({
      "string.pattern.base": "Work end time must be in HH:MM format",
    }),
})
  .min(1)
  .messages({
    "object.min": "At least one field is required for update",
  });

export default {
  updateProfileSchema,
  updateUserRoleSchema,
  updateUserStatusSchema,
  createUserSchema,
  updateEmployeeSchema,
};
